version: '2'

services:
   nginx:
    image: nginx:1.9
    container_name: ci_nginx
    ports:
     - "443:443"
     - "80:80"
    volumes:
     - ./nginx/etc/nginx/crypt:/etc/nginx/crypt
     - ./nginx/etc/nginx/conf.d:/etc/nginx/conf.d
     - ci_nginx_log_dir:/var/log/nginx
    depends_on:
     - jenkins
     - nexus
    links:
     - jenkins:jenkins
     - nexus:nexus
   jenkins:
    image: jenkins:2.0-beta-2
    container_name: ci_jenkins
    environment:
     - JAVA_OPTS=-Xms256m -Xmx256m
    volumes:
     - ci_jenkins_data_dir:/var/jenkins_home
    links:
     - postgresql4tests:postgresql4tests
     - nexus:nexus
   nexus:
    image: sonatype/nexus3:3.0.0
    container_name: ci_nexus
    environment:
     - JAVA_MAX_MEM=-Xmx256m
     - JAVA_MIN_MEM=-Xms256m
    volumes:
     - ci_nexus_data_dir:/nexus-data
   postgresql4tests:
    image : postgres:9.5
    container_name: ci_postgresql4test
    environment:
     - POSTGRES_PASSWORD=postgresqlPassword
    volumes :
     - ci_postgresql4test_data_dir:/var/lib/postgresql/data

volumes:
  ci_jenkins_data_dir:
  ci_nexus_data_dir:
  ci_nginx_log_dir:
  ci_postgresql4test_data_dir:

