version: '2'

services:
   nginx:
    #build: ./nginx
    image: nginx:1.10.1
    container_name: ci_nginx
    ports:
     - "443:443"
     - "80:80"
    volumes:
     - ./nginx/etc/nginx/ssl:/etc/nginx/ssl
     - ./nginx/etc/nginx/conf.d:/etc/nginx/conf.d
     - ci_nginx_log_dir:/var/log/nginx
    depends_on:
     - jenkins
     - nexus
    links:
     - jenkins:jenkins.dev.intranet
     - nexus:nexus.dev.intranet

#docker exec -it jenkins_test cat /var/jenkins_home/secrets/initialAdminPassword
   jenkins:
    #image: jenkins:latest
    build: ./jenkins
    container_name: ci_jenkins
    ports:
     - "8080:8080"
     - "8443:8443"
    environment:
    # an ugly hack to run docker from a host machine in jenkins container ubuntu 14.04
     - LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:/lib/x86_64-linux-gnu:/usr/local/lib/x86_64-linux-gnu:/opt/lib/x86_64-linux-gnu
     - JAVA_OPTS=-Xms256m -Xmx512m
     - JENKINS_OPTS=--httpPort=8080 --httpsPort=8443 --httpsCertificate=/etc/ssl/certs/server.crt --httpsPrivateKey=/etc/ssl/private/server.key
    volumes:
     - ci_jenkins_data_dir:/var/jenkins_home
      #- ./jenkins/src/main/docker/var/jenkins_home/ssl:/var/jenkins_home/ssl
     - /var/run/docker.sock:/var/run/docker.sock
     - /usr/bin/docker:/usr/bin/docker #should point to where $(whick docker) points
     # an ugly hack to run docker from a host machine in jenkins container on ubuntu 14.04
     - /usr/lib/x86_64-linux-gnu:/usr/local/lib/x86_64-linux-gnu
     - /lib/x86_64-linux-gnu:/opt/lib/x86_64-linux-gnu


    links:
     #- postgresql4tests:postgresql4tests
     - nexus:nexus.dev.intranet
     - nexus:nexus-snapshots.dev.intranet
     - nexus:nexus-releases.dev.intranet

   nexus:
    build: ./nexus
    #image: sonatype/nexus3:3.0.0
    container_name: ci_nexus
    environment:
     - JAVA_MAX_MEM=-Xmx256m
     - JAVA_MIN_MEM=-Xms256m
    volumes:
     #- ci_nexus_data_dir:/nexus-data
     - ci_nexus_data_dir:/usr/local/share/nexus/data

   #postgresql4tests:
    #image : postgres:9.5
    #container_name: ci_postgresql4test
    #environment:
     #- POSTGRES_PASSWORD=postgresqlPassword
    #volumes :
     #- ci_postgresql4test_data_dir:/var/lib/postgresql/data

volumes:
  ci_jenkins_data_dir:
  ci_nexus_data_dir:
  ci_nginx_log_dir:
  #ci_postgresql4test_data_dir:
