version: '2'

services:
   nginx:
    image: nginx:1.9
    container_name: ci_nginx
    ports:
     - "443:443"
     - "80:80"
    volumes:
     - ./nginx/etc/nginx/crypt:/etc/nginx/crypt
     - ./nginx/etc/nginx/conf.d:/etc/nginx/conf.d
     - ci_nginx_log_dir:/var/log/nginx
    depends_on:
     - jenkins
     - nexus
    links:
     - jenkins:jenkins
     - nexus:nexus
     
#docker exec -it jenkins_test cat /var/jenkins_home/secrets/initialAdminPassword
   jenkins:
    image: jenkins:latest
    container_name: ci_jenkins
    ports:
     - "8080:8080"
     - "8443:8443"
    environment:
     - JAVA_OPTS=-Xms256m -Xmx256m
     - JENKINS_OPTS=--httpPort=8080 --httpsPort=8443 --httpsCertificate=/var/jenkins_home/ssl/server.crt --httpsPrivateKey=/var/jenkins_home/ssl/server.key
    volumes:
     - ./jenkins/var/jenkins_home:/var/jenkins_home
    links:
     - postgresql4tests:postgresql4tests
     - nexus:nexus
   nexus:
    image: sonatype/nexus3:3.0.0
    container_name: ci_nexus
    environment:
     - JAVA_MAX_MEM=-Xmx256m
     - JAVA_MIN_MEM=-Xms256m
    volumes:
     - ci_nexus_data_dir:/nexus-data
   postgresql4tests:
    image : postgres:9.5
    container_name: ci_postgresql4test
    environment:
     - POSTGRES_PASSWORD=postgresqlPassword
    volumes :
     - ci_postgresql4test_data_dir:/var/lib/postgresql/data

volumes:
  ci_jenkins_data_dir:
  ci_nexus_data_dir:
  ci_nginx_log_dir:
  ci_postgresql4test_data_dir:
